# Generated by Django 2.2.1 on 2019-10-30 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cod_in',
            new_name='num',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ean',
        ),
        migrations.RemoveField(
            model_name='product',
            name='url',
        ),
        migrations.AddField(
            model_name='product',
            name='alt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='comp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='larg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
