# Generated by Django 2.2.1 on 2019-10-30 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20191029_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='obs',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
