# Generated by Django 2.2.1 on 2019-10-30 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_product_obs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='alt',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='comp',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='larg',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
