# Generated by Django 2.2.1 on 2020-01-23 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20191029_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='month_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='pay_date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProductWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Product')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crm.Work')),
            ],
            options={
                'db_table': 'product_work',
            },
        ),
        migrations.CreateModel(
            name='PayOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, null=True)),
                ('due_date', models.FloatField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Customer')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Work')),
            ],
            options={
                'db_table': 'pay_order',
            },
        ),
    ]
