# Generated by Django 2.2.1 on 2020-01-28 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_auto_20200122_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payorder',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='month_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
