# Generated by Django 2.2.1 on 2020-01-28 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_auto_20200127_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='payorder',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pendente'), (2, 'Pago')], default=1),
        ),
        migrations.AddField(
            model_name='productwork',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productwork',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
