# Generated by Django 2.2.1 on 2020-01-29 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_auto_20200128_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payorder',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
