# Generated by Django 2.2.1 on 2020-02-10 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_auto_20200128_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='first_due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
