# Generated by Django 2.2.1 on 2020-02-11 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_customer_person_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productwork',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
