# Generated by Django 2.2.1 on 2020-02-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_productwork_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
