# Generated by Django 2.2.1 on 2020-02-18 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_work_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
